name: api-rag-index-chat
type: gradio-space
sdk: docker

metadata:
  space_id: Chris4K/api-rag-index-chat
  original_url: https://huggingface.co/spaces/Chris4K/api-rag-index-chat

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"
